_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 1.00000000e+00  1.99999996e-02  4.49999988e-01  0.00000000e+00
           -4.00000006e-01  6.12323426e-17 -1.00000000e+00]
          [ 1.00000000e+00 -4.93649170e-02  2.34868273e-01  1.43152177e-01
            3.00879106e-02  9.78617787e-01  2.05687150e-01]
          [ 1.00000000e+00  1.14592545e-01  2.10875675e-01  1.50171369e-01
           -8.16050544e-02  8.78648639e-01 -4.77468938e-01]
          [ 1.00000000e+00 -2.18762800e-01  9.87058133e-02  4.62734476e-02
            1.02556363e-01  4.11274195e-01  9.11511660e-01]
          [ 1.00000000e+00  2.39512131e-01 -1.52951190e-02 -2.57575251e-02
           -4.03346956e-01 -6.37296587e-02 -9.97967184e-01]
          [ 1.00000000e+00  1.00000000e+00 -1.99999996e-02 -1.37371987e-01
            0.00000000e+00 -1.00000000e+00  1.22464685e-16]
          [ 1.00000000e+00  1.00000000e+00 -1.99999996e-02 -3.67664278e-01
            0.00000000e+00 -1.00000000e+00  1.22464685e-16]
          [ 1.00000000e+00  1.00000000e+00 -1.99999996e-02 -2.94541836e-01
            0.00000000e+00 -1.00000000e+00  1.22464685e-16]
          [ 1.00000000e+00  1.00000000e+00 -1.99999996e-02 -4.01867151e-01
            0.00000000e+00 -1.00000000e+00  1.22464685e-16]
          [ 1.00000000e+00  8.82346988e-01 -1.99999996e-02 -2.54912466e-01
            0.00000000e+00 -1.00000000e+00  1.22464685e-16]
          [ 1.00000000e+00  1.94069698e-01 -1.41198277e-01 -1.40252575e-01
           -1.92769870e-01 -5.88326156e-01 -8.08623731e-01]
          [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
            0.00000000e+00  0.00000000e+00  0.00000000e+00]
          [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
            0.00000000e+00  0.00000000e+00  0.00000000e+00]
          [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
            0.00000000e+00  0.00000000e+00  0.00000000e+00]
          [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
            0.00000000e+00  0.00000000e+00  0.00000000e+00]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7268c4c57190>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 200
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/aa228/sb3_roundabout.py
        e:
            93q91fwef90honj80em1q3lmzacgfvfm:
                codePath: aa228/sb3_roundabout.py
                codePathLocal: aa228/sb3_roundabout.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "3936292454400"
                        used: "3358081830912"
                email: hojjunekim@snu.ac.kr
                executable: /home/hojune/miniconda3/envs/aa228/bin/python
                git:
                    commit: 0617102188e98fa59a1e94ffadcfcc3345994fab
                    remote: https://github.com/hojjunekim/HighwayEnv
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-c519c6a7-a8c3-77a0-e631-74bfa15c4d7d
                host: dagobah
                memory:
                    total: "33549447168"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/hojune/AA228/HighwayEnv/aa228/sb3_roundabout.py
                python: CPython 3.10.19
                root: /home/hojune/AA228/HighwayEnv
                startedAt: "2025-12-02T02:59:05.269101Z"
                writerId: 93q91fwef90honj80em1q3lmzacgfvfm
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 22
                - 35
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(5)
algo:
    value: PPO
batch_size:
    value: 32
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x72690f5fb790>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.9
learning_rate:
    value: 0.0005
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0005))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 64
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (15, 7), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=105, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=105, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=256, out_features=5, bias=True)
          (value_net): Linear(in_features=256, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [{''pi'': [256, 256], ''vf'': [256, 256]}]}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x72690f5fb190>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764644346048401605
target_kl:
    value: None
tensorboard_log:
    value: roundabout_ppo/
use_sde:
    value: "False"
verbose:
    value: 2
vf_coef:
    value: 0.5
