_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[ 1.0000000e+00  2.0000000e-02  4.4999999e-01  0.0000000e+00
           -4.0000001e-01  6.1232343e-17 -1.0000000e+00]
          [ 1.0000000e+00  1.2005627e-01  2.0781361e-01  2.8089780e-01
           -1.6227783e-01  8.6588997e-01 -5.0023448e-01]
          [ 1.0000000e+00 -2.1625841e-01  1.0407834e-01  7.9961598e-02
            1.6614762e-01  4.3365973e-01  9.0107673e-01]
          [ 1.0000000e+00  1.0000000e+00 -2.0000000e-02 -4.7069380e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  1.0000000e+00 -2.0000000e-02 -1.7692648e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  1.0000000e+00 -2.0000000e-02 -3.4113932e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  1.0000000e+00 -2.0000000e-02 -1.8549757e-01
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  8.9781284e-01 -2.0000000e-02 -3.5388213e-02
            0.0000000e+00 -1.0000000e+00  1.2246469e-16]
          [ 1.0000000e+00  2.0540585e-01 -1.2413073e-01 -1.7825206e-01
           -2.9496333e-01 -5.1721138e-01 -8.5585767e-01]
          [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
            0.0000000e+00  0.0000000e+00  0.0000000e+00]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f496565b3d0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 200
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/aa228/sb3_roundabout.py
        e:
            1sfrn42j939ecuef03c1d08botcxmyf6:
                codePath: aa228/sb3_roundabout.py
                codePathLocal: aa228/sb3_roundabout.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "3936292454400"
                        used: "3358089592832"
                email: hojjunekim@snu.ac.kr
                executable: /home/hojune/miniconda3/envs/aa228/bin/python
                git:
                    commit: 0617102188e98fa59a1e94ffadcfcc3345994fab
                    remote: https://github.com/hojjunekim/HighwayEnv
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-c519c6a7-a8c3-77a0-e631-74bfa15c4d7d
                host: dagobah
                memory:
                    total: "33549447168"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/hojune/AA228/HighwayEnv/aa228/sb3_roundabout.py
                python: CPython 3.10.19
                root: /home/hojune/AA228/HighwayEnv
                startedAt: "2025-12-02T03:16:21.216464Z"
                writerId: 1sfrn42j939ecuef03c1d08botcxmyf6
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 22
                - 35
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(5)
algo:
    value: PPO
batch_size:
    value: 32
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f49919231f0>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.9
learning_rate:
    value: 0.0005
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0005))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 64
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (10, 7), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=70, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=70, out_features=256, bias=True)
              (1): Tanh()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=256, out_features=5, bias=True)
          (value_net): Linear(in_features=256, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''net_arch'': [{''pi'': [256, 256], ''vf'': [256, 256]}]}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f4991923340>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764645381995607978
target_kl:
    value: None
tensorboard_log:
    value: roundabout_ppo/
use_sde:
    value: "False"
verbose:
    value: 2
vf_coef:
    value: 0.5
